### ISSUE TITLE
Hello, i try the code

### ISSUE THREAD

**Issue by danndaghost** [joshuapinter/flir#1]
Hello, i'm speak spanish, sorry for my english.

I try the code on server, run the php from console 
**php flir.php -i foto.jpg -o test.jpg** 
and display this error.
**PHP Parse error:  syntax error, unexpected end of file in flir.php(124) : eval()'d code on line 1**

¿It's a PHP configuration?

**Comment by sebastianbarria** [comment]
It looks it's a config problem.
It's not specified, but this php requires exiftools and imagemagick installed on the server to work (sudo apt-get install imagemagick libimage-exiftool-perl)

**Comment by joshuapinter** [comment]
Yes, good call. Thanks for replying @sebastianbarria. Do you want to add that to the README file as well?

**Comment by CJP123** [comment]
Hi Joshua
I am having a problem with ir. I read the image file in FIJI and it is scaled 0-65500 rather than in temperature. Am I missing something? is there a version of convert that i should be using?
Thanks

**Comment by joshuapinter** [comment]
@CJP123 Not sure, but if you find out, please post back here to help others.

**Comment by sebastianbarria** [comment]
Hi Joshua.
I'm having problems converting "FLIR ONE" images... every time I try to convert an image taked with that camera, the result image is similar to this:
![test](https://user-images.githubusercontent.com/9473104/37607854-da3d5042-2b77-11e8-87f0-665477646bbf.jpg)

The original image is this one:
![101117185047](https://user-images.githubusercontent.com/9473104/37607770-b35529be-2b77-11e8-94b0-994314016a53.JPG)

I'm executing on SSH with this code and response:
```
php flir.php --scale --resize 100% -i 101117185047.JPG -o test.jpg
Plancks values: 19288.129 0.01404444 1473.9 -2832 1
Atmosph values: 0.006569 0.01262 -0.002276 -0.006677 1.9

RAW Temp Range FLIR setting: 5808 14576
RAW Temp Range select      : 5808 14576

Atmosph : 20.0C 50.0% 3.00m
Tau=0.98944956639731
Reflected Apparent Temperature: 22.0 degree Celsius
Emissivity: 0.9
RAW athmosphere: 11891 / RAW reflected 12207


RAW Temp Range from sensor : 50 65462
wrote "test.jpg" with Temp-Range: -44.3 / 37.4 degree Celsius
```
With other thermal images I have no problem... what could it be?
Thanks!

**Comment by joshuapinter** [comment]
Hi @sebastianbarria, off the top of my head I'm not sure what's going wrong but I'm certainly not an expert. 

I have this repo just so we can all have it open sourced and continue to improve on it so if you find out what's going wrong, please post back here and consider writing a Pull Request to help improve things, even if it's just the documentation.

Thanks!
